pandoc -s^
    -H style\preambolo.tex^
    --number-sections ^
    style\settings.md ^
    Capitoli\lezione_01.md ^
    Capitoli\lezione_02.md ^
    Capitoli\lezione_03.md ^
    Capitoli\lezione_04.md ^
    Capitoli\lezione_05.md ^
    Capitoli\lezione_06.md ^
    Capitoli\lezione_07.md ^
    Capitoli\lezione_08.md ^
    -o out\storia_della_scienza.pdf